In [3]:
import matplotlib.pyplot as plt
from PIL import Image
im = Image.open('1_1.tif')
im.show()

In [10]:
import numpy as np
imarray = np.array(im)

In [11]:
imarray.shape

(420, 580)

In [12]:
imarray.max()

255

In [13]:
imarray.min()

0

In [22]:
imarray.mean()

99.88446633825944

In [14]:
imarray[:5, :5]

array([[  0,  92,  84,  81,  81],
       [  0, 149, 135, 120, 125],
       [  3, 140, 143, 135, 142],
       [  0, 146, 143, 139, 129],
       [  0, 199, 180, 179, 169]], dtype=uint8)

In [16]:
im_mask = Image.open('1_1_mask.tif')
im_mask_array = np.array(im_mask)

In [19]:
im_mask_array.shape

(420, 580)

In [20]:
im_mask_array.min()

0

In [21]:
im_mask_array.max()

255

In [23]:
im_mask_array.mean()

4.832019704433497

In [26]:
im_mask_array.nonzero()

(array([ 84,  84,  84, ..., 170, 170, 170]),
 array([433, 434, 435, ..., 419, 420, 421]))

In [42]:
im_mask_array[80:90, 430:440]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0, 255, 255, 255, 255, 255, 255, 255]], dtype=uint8)

In [33]:
print(im_mask_array.nonzero()[0].min(), im_mask_array.nonzero()[0].max())

84 170


In [34]:
print(im_mask_array.nonzero()[1].min(), im_mask_array.nonzero()[1].max())

400 482
